# generated by datamodel-codegen:
#   filename:  task_assigned_event_schema.json
#   timestamp: 2022-05-19T09:20:55+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import (
    BaseModel,
    Field,
)


class EventTitleTaskAssigned(Enum):
    TASK_ASSIGNED = "TASK.ASSIGNED"


class TaskNewAssigneeDataSchema(BaseModel):
    public_id: str = Field(..., title="Public Id")
    old_assignee_public_id: Optional[str] = Field(
        None, title="Old Assignee Public Id"
    )
    new_assignee_public_id: str = Field(..., title="New Assignee Public Id")


class TaskProducer(Enum):
    POPUG_TASKKEEPER = "POPUG_TASKKEEPER"


class TaskAssignedEventSchema(BaseModel):
    version: Optional[int] = Field(1, title="Version")
    produced_at: Optional[datetime] = Field(None, title="Produced At")
    title: Optional[EventTitleTaskAssigned] = "TASK.ASSIGNED"
    data: TaskNewAssigneeDataSchema
    producer: Optional[TaskProducer] = "POPUG_TASKKEEPER"
