# generated by datamodel-codegen:
#   filename:  user_created_event_schema.json
#   timestamp: 2022-05-19T09:20:55+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import (
    BaseModel,
    Field,
)


class EventTitleUserCreated(Enum):
    USER_CREATED = "USER.CREATED"


class UserRoles3(Enum):
    EMPLOYEE = "EMPLOYEE"
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"


class UserDataSchema(BaseModel):
    public_id: str = Field(..., title="Public Id")
    username: str = Field(..., title="Username")
    email: str = Field(..., title="Email")
    role: UserRoles3


class UserProducer(Enum):
    POPUG_AUTH = "POPUG_AUTH"


class UserCreatedEventSchema(BaseModel):
    version: Optional[int] = Field(1, title="Version")
    produced_at: Optional[datetime] = Field(None, title="Produced At")
    title: Optional[EventTitleUserCreated] = "USER.CREATED"
    data: UserDataSchema
    producer: Optional[UserProducer] = "POPUG_AUTH"
