# generated by datamodel-codegen:
#   filename:  task_updated_event_schema.json
#   timestamp: 2022-05-19T12:02:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import (
    BaseModel,
    Field,
)


class EventTitleTaskCreated(Enum):
    TASK_CREATED = "TASK.CREATED"


class TaskStatus1(Enum):
    OPEN = "OPEN"
    DONE = "DONE"


class UserInfoSchema1(BaseModel):
    public_id: str = Field(..., title="Public Id")


class TaskDataUpdateSchema(BaseModel):
    public_id: str = Field(..., title="Public Id")
    title: Optional[str] = Field(None, title="Title")
    description: Optional[str] = Field(None, title="Description")
    status: Optional[TaskStatus1] = None
    assignee: Optional[UserInfoSchema1] = None
    jira_id: Optional[int] = Field(None, title="Jira Id")


class TaskProducer(Enum):
    POPUG_TASKKEEPER = "POPUG_TASKKEEPER"


class TaskUpdatedEventSchema(BaseModel):
    title: Optional[EventTitleTaskCreated] = "TASK.CREATED"
    data: TaskDataUpdateSchema
    producer: Optional[TaskProducer] = "POPUG_TASKKEEPER"
