"""auto

Revision ID: 0003
Revises: 0002
Create Date: 2022-05-19 15:58:38.110231

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "short_title",
            sa.String(length=50),
            server_default=sa.text("''"),
            nullable=False,
        ),
    )
    op.add_column("tasks", sa.Column("jira_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "jira_id")
    op.drop_column("tasks", "short_title")
    # ### end Alembic commands ###
